### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by ghost** [Bishoy/Mac-Ar-Layout-for-Win#1]
hi there i am a linux user and i use fedora 35 for my laptop and i am used to the mac arabic keyboard layout so i wish if you can help me installing this layout for my linux machine

**Comment by ghost** [comment]
[Update] the Arabic mac layout is available in all Linux distros as Arabic (mackintosh), you can find it in your settings

**Comment by Bishoy** [comment]
Thanks for sharing .
