### ISSUE TITLE
مشكلة النقطة

### ISSUE THREAD

**Issue by aammsh** [Bishoy/Mac-Ar-Layout-for-Win#2]
السلام عليكم
شكرا جزيلا على هذه التوزيع التي خدمتنا كثيرا
توجد ملاحظة مزعجة وهي أنه لا يوجد نقطة في هذه التوزيعة، مفتاح النقطة يظهر هذه ۔ خط صغير وبعد إضافته يتغير حجم الخط ونوعه

أتمنى أن تجد حل لها۔
تحياتي

**Comment by Bishoy** [comment]
تم الحل فى النسخة الجديدة ، https://github.com/Bishoy/Mac-Ar-Layout-for-Win/releases/download/v1.0.1/ar_mac.zip
